key: controlled_application_deployment_via_ci_cd_pipeline
name: Controlled Application Deployment via CI/CD Pipeline
type: AUTOMATED
statement: Application deployments are performed exclusively through the CI/CD pipeline.
regex: kubectl.*set image
rules_summary: MATCH_COUNT GREATER_THAN_OR_EQUAL_TO '1'
validation_rules:
- regexOperation:
    type: MATCH_COUNT
  criteria: GREATER_THAN_OR_EQUAL_TO
  value:
    type: CUSTOM_TEXT
    customText: '1'
evidence_sets:
- EVD-GITLAB-CICD-CONFIG
