#!/usr/bin/env python3
"""
DataDog SIEM Signals Retrieval

Purpose: Retrieve security signals generated by detection rules to prove events are being detected and reviewed.
"""

import json
import logging
import os
import sys
from collections import Counter
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

import requests

from dotenv import load_dotenv

logger = logging.getLogger("datadog_siem_signals")


def current_timestamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def get_env(name: str, default: Optional[str] = None) -> str:
    value = os.environ.get(name, default)
    if value is None or value == "":
        raise RuntimeError(f"Missing required env var: {name}")
    return value


def get_dd_headers() -> Dict[str, str]:
    return {
        "Content-Type": "application/json",
        "DD-API-KEY": get_env("DATADOG_API_KEY"),
        "DD-APPLICATION-KEY": get_env("DATADOG_APP_KEY"),
    }


def get_base_url() -> str:
    return os.environ.get("DATADOG_BASE_URL", "https://api.ddog-gov.com").rstrip("/")


def fetch_all_signals(
    base_url: str,
    headers: Dict[str, str],
    from_ts: str,
    to_ts: str,
) -> List[Dict[str, Any]]:
    all_signals: List[Dict[str, Any]] = []
    cursor: Optional[str] = None
    endpoint = f"{base_url}/api/v2/security_monitoring/signals/search"

    while True:
        body: Dict[str, Any] = {
            "filter": {"from": from_ts, "to": to_ts},
            "page": {"limit": 100},
        }
        if cursor:
            body["page"]["cursor"] = cursor

        try:
            response = requests.post(endpoint, headers=headers, json=body, timeout=30)
            response.raise_for_status()
            payload = response.json()
            data = payload.get("data", [])
            all_signals.extend(data)

            cursor = payload.get("meta", {}).get("page", {}).get("after")
            if not cursor or not data:
                break
        except requests.exceptions.HTTPError as e:
            if e.response is not None and e.response.status_code in (403, 404):
                raise
            logger.warning("Pagination interrupted: %s", e)
            break
        except requests.exceptions.RequestException as e:
            logger.warning("Pagination interrupted: %s", e)
            break

    return all_signals


def extract_signal_fields(signal: Dict[str, Any]) -> Dict[str, Any]:
    attrs = signal.get("attributes", {})
    return {
        "id": signal.get("id"),
        "status": attrs.get("status"),
        "severity": attrs.get("severity"),
        "timestamp": attrs.get("timestamp"),
        "rule_name": attrs.get("rule", {}).get("name"),
        "rule_id": attrs.get("rule", {}).get("id"),
    }


def get_siem_signals() -> Dict[str, Any]:
    base_url = get_base_url()
    headers = get_dd_headers()
    endpoint = f"{base_url}/api/v2/security_monitoring/signals/search"

    lookback_days = int(os.environ.get("DATADOG_SIGNALS_LOOKBACK_DAYS", "30"))
    now = datetime.now(timezone.utc)
    from_dt = now - timedelta(days=lookback_days)
    from_ts = from_dt.strftime("%Y-%m-%dT%H:%M:%SZ")
    to_ts = now.strftime("%Y-%m-%dT%H:%M:%SZ")

    try:
        signals = fetch_all_signals(base_url, headers, from_ts, to_ts)
        extracted = [extract_signal_fields(s) for s in signals]

        severity_counts: Dict[str, int] = dict(Counter(
            s.get("severity", "unknown") or "unknown" for s in extracted
        ))
        status_counts: Dict[str, int] = dict(Counter(
            s.get("status", "unknown") or "unknown" for s in extracted
        ))

        rule_hits: Counter = Counter(
            s.get("rule_name", "unknown") or "unknown" for s in extracted
        )
        top_triggering_rules = [
            {"rule_name": name, "count": count}
            for name, count in rule_hits.most_common(10)
        ]

        return {
            "status": "success",
            "api_endpoint": endpoint,
            "record_count": len(extracted),
            "data": extracted,
            "summary": {
                "total_signals": len(extracted),
                "severity_counts": severity_counts,
                "status_counts": status_counts,
                "top_triggering_rules": top_triggering_rules,
                "lookback_days": lookback_days,
                "date_range": {"from": from_ts, "to": to_ts},
            },
            "retrieved_at": current_timestamp(),
        }

    except requests.exceptions.HTTPError as e:
        if e.response is not None and e.response.status_code in (403, 404):
            return {
                "status": "not_available",
                "message": "Security Monitoring (SIEM) is not enabled for this organization",
                "api_endpoint": endpoint,
                "retrieved_at": current_timestamp(),
            }
        return {"status": "error", "message": str(e), "retrieved_at": current_timestamp()}
    except RuntimeError as e:
        return {"status": "error", "message": str(e), "retrieved_at": current_timestamp()}
    except Exception as e:
        return {"status": "error", "message": str(e), "retrieved_at": current_timestamp()}


def main() -> int:
    logging.basicConfig(
        level=os.environ.get("LOG_LEVEL", "INFO"),
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )
    load_dotenv()

    output_dir = Path(os.environ.get("EVIDENCE_DIR", "./evidence"))
    output_dir.mkdir(parents=True, exist_ok=True)

    result = get_siem_signals()  # keep the original get_XXX() call

    output_json = output_dir / "datadog_siem_signals.json"
    with open(output_json, "w") as f:
        json.dump(result, f, indent=2, default=str)

    logger.info("Evidence saved to %s", output_json)

    return 0 if result.get("status") in {"success", "partial_or_empty", "not_available"} else 1


if __name__ == "__main__":
    sys.exit(main())
