key: passwordless_authenticator_configured
name: Passwordless authenticator configured
type: AUTOMATED
statement: At least one passwordless authenticator is configured.
regex: '"passwordless_authenticators_count"\s*:\s*(\d+)'
rules_summary: MATCH_GROUP[1] GREATER_THAN_OR_EQUAL_TO '1'
validation_rules:
- regexOperation:
    type: MATCH_GROUP
    groupNumber: 1
  criteria: GREATER_THAN_OR_EQUAL_TO
  value:
    type: CUSTOM_TEXT
    customText: '1'
evidence_sets:
- EVD-OKTA-KSI-IAM-02
